version: "3.9"

services:

  api_test:
    container_name: papel_api_test
    image: api_img
    build:
      context: .
      dockerfile: setup/app/Dockerfile
    environment:
      APP_BASE_URL: "${APP_BASE_URL}"
      APP_PORT: "${APP_PORT}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    command: pytest -v
    volumes:
      - ./logs/pytest:/opt/app/logs
    depends_on:
      - db
      - celery

  api_prod:
    container_name: papel_api_prod
    image: api_img   # run with only app_test 1st
#    build:
#      context: .
#      dockerfile: setup/app/Dockerfile
#    env_file:
#      - setup/app/.env
    environment:
      APP_BASE_URL: "${APP_BASE_URL}"
      APP_PORT: "${APP_PORT}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
      CELERY_RESULT_BACKEND: "${CELERY_RESULT_BACKEND}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    command: uvicorn main:app --host 0.0.0.0 --reload
    depends_on:
      - api_test
    ports:
      - "${APP_PORT}:${APP_PORT}"
